name: Check PR Details
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semantic-title:
    runs-on: ubuntu-22.04
    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
