name: Lint GitHub Actions Workflows
on:
  push:
    paths:
      - '.github/workflows/**.yml'

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Lint workflow files
        uses: docker://rhysd/actionlint:1.6.22
        with:
          args: -color

  checkVersions:
    name: Check for pinned verions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@afbf9b485669c7ad13347734c9f146175e83cb43
